---
title: "RGLAB::MEMBERS"
---

### Raphael Gottardo
**Position**: Principal Investigator  
**Interests**: Bayesian modeling, Computational immunology, Flow cytometry, High dimensional modeling, HIV, Malaria, Statistical computing, Single cell assays  
**Websites**: http://www.rglab.org/

### Greg Finak
**Position**: Staff Scientist  
**Interests**: Flow Cytometry, Single-Cell Analysis, Gene Expression, Bayesian Modeling, Statistical Computing, Biomarker Discovery  
**Websites**: https://github.com/gfinak

### Jacob Frelinger
**Position**: Postdoctoral Fellow  
**Interests**: Flow Cytometry, Scientific programming, "Big data"  
**Websites**: https://github.com/jfrelinger

### Lynn Lin
**Position**: Postdoctoral Fellow  
**Interests**: Bayesian statistics, Mixture modeling, Nonparametric Bayesian, Bayesian hypothesis testing, Statistical methods for large datasets, Statistics for immunology, Flow cytometry  
**Websites**: http://stat.duke.edu/~ll86/

### Sangsoon Woo
**Position**: Postdoctoral Fellow  
**Interests**: ChIP-seq, Epigenomics, Gene expression, Next generation sequencing  

### Greg Imholte
**Position**: PhD Student, University of Washington  
**Interests**: Bayesian modeling, Scientific programming, Statistical learning, Stochastic processes  

### Andrew McDavid
**Position**: PhD Student, University of Washington  
**Interests**: Inference from heterogeneous samples with hierarchical models  

### Lev "Leo" Dashevkiy
**Position**: System Analyst / Scientific Programmer  
**Interests**: Flow cytometry, Data visualization, Scientific programming and computing, Client-side web development, Database design, R, JavaScript, SQL, LabKey  
**Websites**: https://github.com/ldash

### Mike Jiang
**Position**: System Analyst / Scientific Programmer  
**Interests**: Flow cytometry, Scientific programming, R, C++  
**Websites**: https://github.com/mikejiang

### Renan Sauteraud
**Position**: System Analyst / Scientific Programmer  
**Interests**: ChIP-seq, Peptide microarray, Next generation sequencing, Scientific programming, Data visualization, Data analysis  

### Jingyuan Deng
**Position**: Bioinformatician  
**Interests**: Next-generation sequencing, Microarray data analysis  

### Phu Van
**Position**: Postdoctoral Fellow  
**Interests**: Flow cytometry, Data visualization, Data analysis  
**Websites**: https://github.com/ptvan


## Alumni
- [Kevin Ushey](http://kevinushey.github.io/), Data scientist at RStudio
- [John Ramey](http://blacklocus.com/), Data scientist at Blacklocus
- [Arnaud Droit](https://www.linkedin.com/in/drarnaud), Assistant Professor at Université Laval
- [Marie-Pier Scott-Boyer](http://www.cosbi.eu/people/people-research/marie-pier-scott-boyer), Postdoctoral Fellow at The Microsoft Research - University of Trento Centre for Computational and Systems Biology
- [Eloi Mercier](https://www.linkedin.com/pub/eloi-mercier/74/2b5/7b6), Computational Biologist at BC Cancer Agency
- [Xiaohui Chen](http://publish.illinois.edu/xiaohuichen/), Assistant Professor, Department of Statistics, University of Illinois at Urbana-Champaign
- [Francois Caron](http://www.stats.ox.ac.uk/~caron/), Research Fellow, Department of Statistics, Oxford University
- [Luke Bornn](http://www.people.fas.harvard.edu/~bornn/), Assistant Professor, Department of Statistics, Harvard University
- [Kaida Ning](https://www.linkedin.com/pub/kaida-ning/14/4a3/b6), PhD student at USC
- [Kenneth Lo](https://www.linkedin.com/in/kenchlo), Data scientist at eBay