---
title: "RGLAB::PUBLICATIONS"
output:
  html_document:
    toc: true
    toc_float: true
---

## 2015

- Florian Hladik, Adam Burgener, Lamar Ballweber, Raphael Gottardo, Slim Fourati, James Y. Dai, Mark J. Cameron, Lucia Vojtech, Johanna Strobl, Sean Hughes, M.A., Craig Hoesley, Ross Cranston, Philip Andrew, Jeanna Piper, T. Blake Ball, Gustavo F. Doncel, David R. Friend, Kenneth Mayer, M. Juliana McElrath, and Ian McGowan. Systems Biology Reveals Significant Mucosal Side Effects of Tenofovir 1% Gel in a Phase I Rectal Microbicide Trial. eLife, In Press.
- Lin Lin, Greg Finak, Kevin Ushey, Chetan Seshadri, Thomas R. Hawn, Nicole Frahm, Thomas J. Scriba, Hassan Mahomed, Willem Hanekom, Pierre-Alexandre Bart, Giuseppe Pantaleo, Georgia Tomaras, Supachai Rerks-Ngarm, Jaranit Kaewkungwal, Sorachai Nitayanphan, Punnee Pitisuttithum, Nelson L. Michael, Jerome H. Kim, Merlin L. Robb, Robert J. O’Connell, Nicos Karasavvas, Bart Haynes, Peter Gilbert, Stephen DeRosa, Julie McElrath and Raphael Gottardo. Combinatorial Polyfunctionality Analysis of Antigen-Specific T-cell Subsets Identifies Novel Cellular Subsets Correlated with Clinical Outcomes. Nature Biotechnology, In Press.
- Carey V, Carlson M, Corrada Bravo H, Carvalho BS, Davis S, Gatto L, Gentleman R, Girke T., Gottardo R., Hahne F., Hansen K., Huber W., Irizarry R. A., Lawrence M., MacDonald J, Obenchain V, Koles A, Pages H, Shannon P, Tenenbaum D, Waldron L, Morgan M. Orchestrating high-throughput genomic analysis with Bioconductor. Nature Methods, In Press.
- Lin Lin, Jacob Frelinger, Mike Jiang, Greg Finak, Chetan Seshadri, Pierre-Alexandre Bart, Giuseppe Pantaleo, Julie McElrath, Steve DeRosa, and Raphael Gottardo. Identification and visualization of multidimensional antigen-specific T-cell populations in polychromatic cytometry data. Cytometry A, In Press.
- Malek M, Taghiyar MJ, Chong L, Finak G, Gottardo R, Brinkman RR. flowDensity: reproducing manual gating of flow cytometry data by automated density-based cell population identification. Bioinformatics. 2015, 10.1093/bioinformatics/btu677. Epub ahead of print. PMID: 25378466.
- Courtot M, Meskas J, Diehl AD, Droumeva R, Gottardo R, Jalali A, Renani JT, Maecker HT, McCoy JP, Ruttenberg A, Scheuermann RH, Brinkman RR. flowCL: ontology-based cell population labelling in flow cytometry. Bioinformatics. 2015, 10.1093/bioinformatics/btu807. Epub ahead of print. PMID: 25481008.
- Paul T. Edlefsen, Morgane Rolland, Tomer Hertz, Andrew Gartland, Allan C. deCamp, Craig A. Magaret, Hasan Ahmed, Raphael Gottardo, Michal Juraska, Frederick A. Matsen IV, Connor McCoy, Brendan B. Larsen, Sodsai Tovanabutra, Eric Sanders-Buell, Chris Carrico, Sergey Menis, Lennie Chen, Philip Konopa, Snehal Nariya, Julia N. Stoddard, Kim Wong, Hong Zhao, Wenjie Deng, Brandon S. Maust, Meera Bose, Shana Howell, Adam Bates, Michelle Lazzaro, Annemarie O’Sullivan, Esther Lei, Andrea Bradfield, Grace Ibitamuno, Vatcharain Assawadarachai, Robert J. O’Connell, Mark S. deSouza, Sorachai Nitayaphan, Supachai Rerks-Ngarm, Merlin L. Robb, Jason S. McLellan, Ivelin Georgiev, Peter D. Kwong, Jonathan M. Carlson, Nelson L. Michael, William R. Schief, James I. Mullins, Jerome H. Kim, and Peter B. Gilbert. Comprehensive sieve analysis of breakthrough HIV-1 sequences in the RV144 vaccine efficacy trial. PLoS Computational Biology, In Press.
- Ann Dahlberg, Sangsoon Woo, Colleen Delaney, Patrick Boyle, Andreas Gnirke, Christoph Bock, Bradley Bernstein, Alex Meissner, Raphael Gottardo, and Irwin Bernstein. Notch-mediated expansion of cord blood progenitors: maintenance of transcriptional and epigenetic fidelity. Leukemia, In Press.


## 2014

- Lemos MP, Lama JR, Karuna ST, Fong Y, Montano SM, Ganoza C, Gottardo R, Sanchez J, McElrath MJ. The inner foreskin of healthy males at risk of HIV infection harbors epithelial CD4+ CCR5+ cells and has features of an inflamed epidermal barrier. PLoS One. 2014;9(9):e108954. PMCID: PMC4182607.
- Zolla-Pazner S, Edlefsen PT, Rolland M, Kong X, deCamp A, Gottardo R, Williams C, Tovanabutra S, Mullins JI, deSouza MS, Karasavvas N, Nitayaphan S, Rerks-Ngarm S, Pitisuttithum P, Kaewkungwal J, O’Connell RJ, Robb ML, Michael NL, Kim JH, Gilbert PB. Vaccine-induced human antibodies specific for the third variable region of HIV-1 gp120 impose immune pressure on infecting viruses. eBioMedicine>. 2014;1(1):37-45. PMCID: PMC4293639.
- Finak G, Frelinger J, Jiang W, Newell EW, Ramey J, Davis MM, Kalams SA, De Rosa SC, Gottardo R. OpenCyto: An Open Source Infrastructure for Scalable, Robust, Reproducible, and Automated, End-to-End Flow Cytometry Data Analysis. PLoS Computational Biology, In Press.
- McDavid A, Dennis L, Danaher P, Finak G, Krouse M, Wang A, Webster P, Beechem J, Gottardo R. Modeling bi-modality improves characterization of cell cycle on gene expression in single cells. PLoS Computational Biology, In Press. 
- Li SS, Gilbert PB, Tomaras GD, Kijak G, Ferrari G, Thomas R, Pyo C-W, Zolla-Pazner S, Montefiori D, Liao H-X, Nabel G, Pinter A, Evans DT, Gottardo R, Dai JY, Janes H, Morris M, Fong Y, Edlefsen PT, Li F, Frahm N, Alpert MD, Prentice H, Rerks-Ngarm S, Pitisuttithum P, Kaewkungwal J, Nitayaphan S, Robb ML, O'Connell RJ, Haynes BF, Michael NL, Kim JH, McElrath MJ, Geraghty DE. Association of FCGR2C polymorphisms with vaccine efficacy and correlates of HIV-1 infection risk in the RV144 trial. Journal of Clinical Investigation, In Press.
- Gartland A, Li S, McNevin J, Tomaras GD, Gottardo R, Janes H, Fong Y, Morris D, Geraghty DE, Kijak GH, Edlefsen PT, Frahm F, Larsen BB, Tovanabutra S, Sanders-Buell E, deCamp AC, Magaret CA, Ahmed H, Goodridge JP, Chen L, Konopa P, Nariya S, Stoddard JN, Wong K, Zhao H, Deng W, Maust BS, Bose M, Howell S, Bates A, Lazzaro M, O’Sullivan A, Lei E, Bradfield A, Ibitamuno G, Assawadarachai V, O’Connell RJ, deSouza MS, Nitayaphan S, Rerks-Ngarm S, Robb ML, Sidney J, Sette A, Zolla-Pazner S, Montefiori DC, McElrath MJ, Mullins JI, Kim JH, Gilbert PB, Hertz T. Analysis of HLA A*02 association with vaccine efficacy in the RV144 Thai trial. Journal of Virology. 2014;88(15):8242-55. 
- Roederer M, Keele BF, Schmidt SD, Mason RD, Welles HC, Fischer W, Labranche C, Foulds KE, Louder MK, Yang ZY, Todd JP, Buzby AP, Mach LV, Shen L, Seaton KE, Ward BM, Bailer RT, Gottardo R, Gu W, Ferrari G, Alam SM, Denny TN, Montefiori DC, Tomaras GD, Korber BT, Nason MC, Seder RA, Koup RA, Letvin NL, Rao SS, Nabel GJ, Mascola JR. Immunological and virological mechanisms of vaccine-mediated protection against SIV and HIV. Nature. 2014;505:502-8.
- Vojtech L, Woo S, Hughes S, Levy C, Ballweber L, Sauteraud RP, Strobl J, Westerberg K, Gottardo R, Tewari M, Hladik F. Exosomes in human semen carry a distinctive repertoire of small non-coding RNAs with potential regulatory functions. Nucleic Acids Research. 2014;42(11):7290-304.
- Finak G, Jiang M, Krouse K, Phippard D, Asare A, DeRosa SC, Self S, Gottardo R. High throughput flow cytometry data normalization for clinical trials. Cytometry A, 2014;85(3):277-86.
- Brusic* V., Gottardo R.*, Kleinstein S.H., Davis M.M., and the HIPC steering committee. Computational resources for high-dimension immune analysis from the Human Immunology Project Consortium. Nature Biotechnology, 2014;32(2):146-8. *Equal contribution
- deCamp A, Hraber P, Bailer RT, Seaman MS, Ochsenbauer C, Kappes J, Gottardo R, Edlefsen P, Self S, Tang H, Greene K, Gao H, Daniell X, Sarzotti-Kelsoe M, LaBranche C, Mascola JR, Korber BT, Monteﬁori DC. Global Panel of HIV-1 Env Reference Strains for Standardized Assessments of Vaccine-Elicited Neutralizing Antibodies. Journal of Virology, 2014;88(5):2489-507.


## 2013

- Woo, S, Zhang, X, Sauteraud, R, Robert, F. and Gottardo, R. PING: An R/Bioconductor package for nucleosome positioning using next-generation sequencing data (2013). Bioinformatics, 2013;29(16):2049-50.
- Finak, G., McDavid A., De Rosa, S., Chattopadhyay, P., Dominguez, M., Roederer, M. and Gottardo, R. Mixture Models for Single-Cell Assays with Application to Vaccine Studies (2013). Biostatistics, 2014;85(3):277-86.
- Greg C. Imholte, Renan Sauteraud, Bette Korber, Robert T. Bailer, Ellen T. Turk, Georgia Tomaras, Shauna Shen, John Mascola, Richard Koup, David Montefiori, and Raphael Gottardo. A computational framework for the analysis of peptide microarray antibody binding data with application to HIV vaccine profiling (2013). Journal of Immunological Methods, 2013;395(1-2):1-13.
- Dominguez,MH, Chattopadhyay, PK, Ma, S, Lamoreaux, L, McDavid, A, Finak, G, Gottardo, R, Koup, RA, Roederer, M. Highly Multiplexed Quantitation of Gene Expression on Single Cells. Journal of Immunological Methods, 391(1-2): 133–145 
- McDavid, A, Finak, G, Chattopadyay, PK, Dominguez, M, Lamoreaux, L, Ma, SS, Roederer, M, and Gottardo, R. Data exploration, quality control and testing in single-cell qPCR-based gene expression experiments. Bioinformatics, 29(4): 461-467 
- Aghaeepour, N, Finak, G, The FlowCAP Consortium, The DREAM Consortium, Hoos, H, Mosmann, TR, Brinkman, R, Gottardo, R, and Scheuermann, RH. Critical assessment of automated flow cytometry data analysis techniques. Nature Methods, 10: 228–238 
- Casazza, Joseph P; Bowman, Kathryn; Adzaku, Selorm; Smith, Emily C; Enama, Mary E; Bailer, Robert T; Price, David A; Gostick, Emma; Gordon, Ingelise; Ambrozak, David R; Nason, Martha; Roederer, Mario; Andrews, Charla A; Maldarelli, Frank M; Wiegand, Ann; Kearney, Mary F; Persaud, Deborah; Ziemniak, Carrie; Gottardo, Raphael; Ledgerwood, Julie E; Graham, Barney S; Koup, Richard A. Therapeutic Vaccination Expands and Improves the Function of the HIV-specific Memory T Cell Repertoire. Journal of Infectious Diseases 2013;207(12):1829-40 
- Susan Zolla-Pazner, Timothy Cardozo, Nicos Karasavvas, Raphael Gottardo, Constance Williams, Daryl E Morris, Georgia Tomaras, Mangala Rao, Erik Billings, Phillip Berman, Xiaoying Shen, Charla Andrews, Robert J O'Connell, Viseth Ngauy, Sorachai Nitayaphan, Mark de Souza, Bette Korber, Richard Koup, Robert T Bailer, John R Mascola, Abraham Pinter, David Montefiori, Barton F Haynes, Merlin L Robb, Supachai Rerks-Ngarm, Nelson L Michael, Peter B Gilbert, Jerome H Kim. Analysis of V2 Antibody Responses Induced in Vaccinees in the ALVAC/AIDSVAX HIV-1 Vaccine Efficacy Trial/ PLoS One 8(1):e53629 


## 2012

- Huang, Y. and Gottardo, R. (2012). Comparability and reproducibility of biomedical data. Briefings in Bioinformatics. 
G. Finak, W. Jiang, J. Pardo, A. Asare, R. Gottardo (2012) QUAliFiER: An automated pipeline for quality assessment of gated flow cytometry data BMC Bioinformatics DOI: 10.1186/1471-2105-13-252 
- Nicos Karasavvas, Erik Billings, Mangala Rao, Constance Williams, Susan Zolla-Pazner, Robert Bailer, Richard Koup, Sirinan Madnote, Duangnapa Arworn, Xiaoying Shen, Georgia Tomaras, Jeffrey Currier, Mike Jiang, Craig Magaret, Charla Andrews, Raphael Gottardo, Peter Gilbert, Timothy Cardozo, Supachai Rerks-Ngarm, Sorachai Nitayaphan, Punnee Pitisuttithum, Jaranit Kaewkungwal, Robert Paris, Kelli Greene, Hongmei Gao, Sanjay Gurunathan, Jim Tartaglia, Faruk Sinangil, Bette Korber, David Montefiori, John Mascola, Merlin Robb, Barton Haynes, Viseth Ngauy, Nelson Michael, Jerome Kim, and Mark de Souza (2012). The Thai phase III HIV-1 vaccine trial (RV144) regimen induces antibodies that target the crown of the V2 loop of gp120. AIDS Research and Human Retroviruses, 2012;28(11):1444-57.
- Arafat Tayeb, Marie-Pier Scott-Boyer, Aurelie Labbe, Christian Deschepper, Raphael Gottardo (2012). An integrated Bayesian Model for Multivariate eQTL Mapping. Statistical Applications in Genetics and Molecular Biology, 11:1544-6115. 
- X. Zhang, G. Robertson, S Woo, BG Hoffman, R Gottardo (2012) Probabilistic inference for nucleosome positioning with MNase-based or sonicated short-read data. PLoS ONE. 2012;7(2):e32095. 
- K. Lo and R. Gottardo (2012). Flexible Mixture Modeling via the Multivariate t Distribution with the Box-Cox Transformation: An Alternative to the Skew t Distribution. Statistics and Computing, 22(1): 33-52. 
- A. Bashashati, N.A. Johnson, A. Hadj Khodabakhshi , M. Whiteside, H. Zare, D.W. Scott, K. Lo, R. Gottardo, F. Brinkman, J. Connors, G. Slack, R.D. Gascoyne, A. Weng, R.R. Brinkman (2012) B-cells with high side scatter parameter by flow cytometry correlate with inferior survival in diffuse large B cell lymphoma. American Journal of Clinical Pathology: 137 (5): 805-814. 


## 2011

- F. Caron, A. Doucet, and R. Gottardo (2011). On-line changepoint detection and parameter estimation with application to genomic data. Statistics and Computing 22:579–595. 
- X. Zhang, G. Robertson, M. Krzywinski, K. Ning, A. Droit, S. Jones, and R. Gottardo (2011). PICS: Probabilistic Inference for ChIP-seq. Biometrics: 67 (1): 151-163. 
- Mercier E, Droit A, Li L, Robertson G, Zhang X, and Gottardo R (2011) An Integrated Pipeline for the Genome-Wide Analysis of Transcription Factor Binding Sites from ChIP-Seq. PLoS ONE 6(2): e16432. doi:10.1371/journal.pone.0016432 


## 2010

- Finak, G. and Manuel-Perez, J. and R. Gottardo (2010). Automated transformations for flow cytometry. BMC Bioinformatics, 11:546. 
- K. Lo and R. Gottardo (2009). Flexible Mixture Modeling via the Multivariate t Distribution with the Box-Cox Transformation: An Alternative to the Skew t Distribution, Statistics and Computing, DOI: 10.1007/s11222-010-9204-1. 
- J.P. Baudry, A.E. Raftery, G. Celeux, K. Lo and R. Gottardo (2010). Combining Mixture Components for Clustering. Journal of Graphical and Computational Statistics, 19: 332:353. 
- B. Luke, A. Doucet and R. Gottardo (2010). An Efficient Computational Approach for Prior Sensitivity Analysis and Cross-Validation. Canadian Journal of Statistics, 38: 47 - 64. 
- A. Droit, C. Cheung, and R. Gottardo (2010). rMAT – an R/Bioconductor package for analyzing ChIP-chip experiments, Bioinformatics, 26:678-679. 


## 2009

- Gottardo, R., Brinkman, R.R., Luta, G. and Wand, M.P. (2009). Recent bioinformatics advances in the analysis of high throughput flow cytometry data. Editorial article. Advances In Bioinformatics, doi:10.1155/2009/461763 
- G. Finak, A. Bashashati, R. Brinkman, R. Gottardo (2009). Merging Mixture Components for Cell Population Identification in Flow Cytometry. Advances in Bioinformatics, doi:10.1155/2009/247646 
- K. Lo, F. Hahne, R. Brinkman and R. Gottardo (2009). flowClust: a Bioconductor package for automated gating of ﬂow cytometry data. BMC Bioinformatics, 10: R145. 
- R. Gottardo and A. E. Raftery (2009) Bayesian robust variable and transformation selection: A unified approach, Canadian Journal of Statistics, 37: 1-20. 
- R. Gottardo (2009). Statistical methods for ChIP experiments on microarrays. Humana Press, vol. 567. This chapter will be part of a Volume in the Methods in Molecular Biology series on “Chromatin Immuno-precipitation Assays” edited by Phillipe Collas and published by Humana Press. 
- R. Gottardo (2009). Bayesian Robust Inference for Differential Gene Expression (In Press). This chapter will be part of a book on “Bayesian Modeling in Bioinformatics” edited by Dipak Dey, Samiran Ghosh and Banni Mallick, and published by Taylor and Francis. 
- A. Bashashati, K. Lo, R. Gottardo, R. Gascoyne, A. Weng, R. Brinkman (2009). A Pipeline for Automated Analysis of Flow Cytometry Data: Preliminary Results on Lymphoma Sub-Type Diagnosis, IEEE Engineering in Medicine and Biology Society (EMBC’09). 
- X. Chen and R. Gottardo. An MM-Based Optimization Algorithm for Sparse Linear Modeling on Microarray Data Analysis, 3rd International Conference on Bioinformatics and Biomedical Engineering. ICBBE 2009. 


## 2008
- V. T. Chu, R. Gottardo, A. E. Raftery, R. E. Bumgarner and K. Y. Yeung (2008). MeV+R: Using MEV as a GUI for Bioconductor application. Genome Biology 9:R118. 
- R. Gottardo, A. E. Raftery (2008). Markov chain Monte Carlo with mixtures of singular distributions. Journal of Computational and Graphical Statistics 17:917-943. 
- K. Lo, R. Brinkman and R. Gottardo (2008). Automated gating of ﬂow cytometry data via robust model based clustering. Cytometry A, 73:321-332. 
- R. Gottardo, Li, W., Liu, S. and Johnson, E. (2008). A flexible and powerful Bayesian hierarchical model for ChIP-chip experiments. Biometrics, 64:468-78. 


## 2007

- K. Lo and R. Gottardo (2007). Flexible empirical Bayes models for differential gene expression. Bioinformatics 23: 328. 


## 2006

- W. E. Johnson, Li, W., Meyer, C. A., Gottardo, R., Carroll, J. S., Brown, M., and Liu, X. S. (2006). Model-based analysis of tiling-arrays for ChIP-chip. PNAS 103:12457-12462.
- R. Gottardo, A. E. Raftery, K. Y. Yeung and R. Bumgarner (2006). Quality Control and Robust Estimation for cDNA Microarrays with Replicates. Journal of the American Statistical Association, 101:30-40. 
- R. Gottardo, J. Besag, M. Stephens and A. Murua (2006). Probabilistic segmentation and intensity estimation for microarray images. Biostatistics, 7:85-99.
- R. Gottardo, A. E. Raftery, K. Y. Yeung and R. Bumgarner (2006). Bayesian robust inference for differential gene expression in cDNA microarrays with multiple samples. Biometrics, 62:10-18. 


## 2004

- J. F. Challacombe, A. Rechtsteiner, R. Gottardo, L. M. Rocha, E. P. Browne, T. Shenk, M. R. Altherr, and T. S. Brettin (2004). Evaluation of the host transcriptional response to human cytomegalovirus infection. Physiol. Genomics, 18:51-62. 


## 2003

- R. Gottardo, J. A. Pannucci, C. R. Kuske and T. Brettin (2003). Statistical analysis of microarray data: A Bayesian approach. Biostatistics, 4:597-620.
- G. Xie, C. A. Bonner, T. Brettin, R. Gottardo, N. O. Keyhani and R. A. Jensen (2003). Lateral gene transfer and ancient paralogy of operons containing redundant copies of tryptophan-pathway genes in Xylella species and in heterocystous cyanobacteria. Genome Biology, 4:R14.